### ISSUE TITLE
Add SMTP Sever

### ISSUE THREAD

**Issue by Rishabh-malhotraa** [Rishabh-malhotraa/Vita#10]
Incorporate SMTP server to send emails to mentor-mentee when their booking is confirmed and also reminder email 30 minutes before the meeting 

Also in the confirmed meeting email send an ics file
https://www.npmjs.com/package/ics

https://nodemailer.com/about/

https://www.youtube.com/watch?v=nF9g1825mwk

**Comment by hazemessam** [comment]
I'm interested to work on it under GSSoC

**Comment by lokita282** [comment]
i'm a gssoc '22 participant and would like to work on this issue

**Comment by amir-ammar** [comment]
i'm a gssoc '22 participant and would like to work on this issue

**Comment by Rishabh-malhotraa** [comment]
@lokita282 @amir-ammar can you please tell me how do you plan to solve this issue, so we are on the same page, I'll assign you the issue once I'm happy that you understand what to do!

**Comment by amir-ammar** [comment]
i will use ics to create the calendar event and then using nodemailer to send mails

**Comment by Rishabh-malhotraa** [comment]
can you check if you can programmatically create a google meet/ zoom call link and add that to the ics file or mail

**Comment by amir-ammar** [comment]
yeah i can

**Comment by lokita282** [comment]
I think to programmatically create a  google meet, we can use the google calendar api, and add that to the .ics file

**Comment by hazemessam** [comment]
@Rishabh-malhotraa 
Please, assign it to me

**Comment by hazemessam** [comment]
@Rishabh-malhotraa I am sorry for my late. I will start working on it by tomorrow.

**Comment by SatabrataPaul-GitAc** [comment]
Hello 
I am Satabrata Paul 
Currently I have contributed to few projects in the past 2 weeks in GSSOC'22. 
I would like to work for Vita on this issue 
Can you please assign it to me

**Comment by hazemessam** [comment]
> Hello I am Satabrata Paul Currently I have contributed to few projects in the past 2 weeks in GSSOC'22. I would like to work for Vita on this issue Can you please assign it to me

I'm currently working on it.
