### ISSUE TITLE
Replace the Card Grid with Carousel

### ISSUE THREAD

**Issue by Sahaj-Srivastava24** [Rishabh-malhotraa/Vita#21]
A Card Carousel could replace the Card Grid display scheme for displaying mentors and topics. The cards can be lazily loaded whenever they pop on the viewport and have a hover transition to display further links. The carousel would have the feature to scroll infinitely. A library could implement the whole carousel called [Swiper JS](https://swiperjs.com/).

**Comment by Rishabh-malhotraa** [comment]
Hello @Sahaj-Srivastava24 

What we require is to

- **add a carousel component on the landing page**, we don't really need to change the Card grid on the search mentor page. you can check how it's done on [adplist's](https://adplist.org/) landing page.
- Swiper JS looks nice, it has a react wrapper too. Originally I was also thinking of not using a heavy library and just using react-transition groups or react-spring for animation and adding our own logic for carousel rendering. **Maybe look into that first.**



To be clear we want something like this

<img width="1013" alt="image" src="https://user-images.githubusercontent.com/54576074/149085145-e982fa5f-3e8c-4d2c-a767-e3ffbb542160.png">

https://user-images.githubusercontent.com/54576074/149085512-c8b1a9b0-e303-4611-9db0-290fddc74032.mp4

---

**I remember I have already made this component, but then removed it, you can check it out [here](https://github.com/Rishabh-malhotraa/Vita/blob/3d4adbdc8c24c2e6e67cc2e0866de621f73260ab/client/src/components/DEPRECATED_Pagination/index.tsx)**
<img width="971" alt="image" src="https://user-images.githubusercontent.com/54576074/149085760-6da70fda-f402-49f1-bd1a-59500a301988.png">

**Comment by sulogna2001** [comment]
Hey Can you assign me this issue for GSsoc22

**Comment by Rishabh-malhotraa** [comment]
Hello @sulogna2001, we already have a PR in progress for this. Do you mind working on some other issue, thank you!
