### ISSUE TITLE
Add Login Page

### ISSUE THREAD

**Issue by Devansh-365** [Rishabh-malhotraa/Vita#22]
Adding a login page and giving the option to users of logging in with their Google, GitHub, Twitter, email account can make the process easier to access their data.

Login Page contains: 
👉Login with Email
👉Login with Github
👉Login with Twitter
👉Login with Google

**Comment by Rishabh-malhotraa** [comment]
<img width="834" alt="image" src="https://user-images.githubusercontent.com/54576074/149653811-626e8669-286c-4bea-9629-fcf3dbd51941.png">

we only need login from google and linkedIn

**Comment by Maneet-k** [comment]
@Rishabh-malhotraa  Can I work on this?

**Comment by sulogna2001** [comment]
Hey Can you assign me this issue for GSsoc22

**Comment by sagnik2001** [comment]
Can I work on this under GSSoC 22

**Comment by yogitasaini** [comment]
Please assign this task to me for GSSoC22

**Comment by Anish-Parkhi** [comment]
Hey can you assign me this task for GSSoC 22
I also have made a wireframe to get idea
![Login-Page-Demo](https://user-images.githubusercontent.com/93964690/156150020-2729071b-1cd7-4fa5-b2f6-eb2447106a46.PNG)

**Comment by gayatrisakure** [comment]
Can I work on this issue for GSSoC'22 ?

**Comment by Saba2402** [comment]
Please assign this issue to me .I want to work over it under GSSoc

**Comment by Rishabh-malhotraa** [comment]
@gayatrisakur this is the design we are thinking of implememting
Maybe @Lalit3716 and you can work together on this

 ![image](https://user-images.githubusercontent.com/54576074/156939285-bcec7222-0b5b-4e6f-b422-db221c9cc037.png)

**Comment by Lalit3716** [comment]
> @gayatrisakur this is the design we are thinking of implememting Maybe @Lalit3716 and you can work together on this
> 
> ![image](https://user-images.githubusercontent.com/54576074/156939285-bcec7222-0b5b-4e6f-b422-db221c9cc037.png)

I would love to work on this with @gayatrisakure If he allows that.

**Comment by gayatrisakure** [comment]
> @gayatrisakur this is the design we are thinking of implememting Maybe @Lalit3716 and you can work together on this
> 
> ![image](https://user-images.githubusercontent.com/54576074/156939285-bcec7222-0b5b-4e6f-b422-db221c9cc037.png)

@Rishabh-malhotraa It would be my pleasure working with @Lalit3716.

**Comment by gayatrisakure** [comment]
> > @gayatrisakur this is the design we are thinking of implememting Maybe @Lalit3716 and you can work together on this
> > ![image](https://user-images.githubusercontent.com/54576074/156939285-bcec7222-0b5b-4e6f-b422-db221c9cc037.png)
> 
> I would love to work on this with @gayatrisakure If he allows that.

@Rishabh-malhotraa it would be my pleasure working with @Lalit3716 . I am ready to work with him

**Comment by gayatrisakure** [comment]
> @gayatrisakur this is the design we are thinking of implememting Maybe @Lalit3716 and you can work together on this
> 
> ![image](https://user-images.githubusercontent.com/54576074/156939285-bcec7222-0b5b-4e6f-b422-db221c9cc037.png)

@Rishabh-malhotraa it would be my pleasure working with @Lalit3716 . i would like to work with him.

**Comment by Lalit3716** [comment]
@gayatrisakure cool! Can you tell me your discord name so we can connect ?
