### ISSUE TITLE
Add Workflows for acknowledging Pull Request!

### ISSUE THREAD

**Issue by Rishabh-malhotraa** [Rishabh-malhotraa/Vita#32]
Add Github bots to do some smart features
<img width="997" alt="image" src="https://user-images.githubusercontent.com/54576074/155955308-02b0b157-606d-4f66-922c-dee43565f3cd.png">

You can see how it's being implemented in this [repo](https://github.com/Suvraneel/Automated-assign-labeler).

**Comment by jalanprakhar** [comment]
claim

**Comment by artimanputra** [comment]
I would like to work on the issue, can you please assign it to me?

**Comment by Devansh-365** [comment]
Hey Can you please assign it to me..

**Comment by Rishabh-malhotraa** [comment]
@Devansh-365 Can we please get this done before 2 March, I would like to have these bots setup before the GSSOC'22 starts

**Comment by Rishabh-malhotraa** [comment]
> I would like to work on the issue, can you please assign it to me?

Hello @artimanputra, sorry for the confusion, but I created this issue to give it to @Devansh-365 in mind; I had talked to him on discord about it!
I hope you don't mind!

**Comment by Rishabh-malhotraa** [comment]
> If issue is not completed then please consider me eligible for that. 

Do you have experience with setting up github actions and CI/CD pipelines?

You can go through these resources
https://rishabh-malhotra.notion.site/Level-3-Intermediate-6b2ffc0c6f4f46faadf2262c2bc447d3#ac4f9510af234f93bb01e45e2872cc46


Then try to set it up

**Comment by HarshKumarChoudary** [comment]
I created the PR. Please check for it and merge it.

**Comment by Jassi10000** [comment]
@Rishabh-malhotraa You could have assigned me , I also opened the issue 3 days ago as well
