### ISSUE TITLE
Fix typo error in "Card Description Under Topics"

### ISSUE THREAD

**Issue by indraantoor** [Rishabh-malhotraa/Vita#33]
**Describe the bug**
There is a **typo** in the card description of the card with title "**Getting the most out of my internship**". It's written "**intership**" in the description and instead it should be "**internship**". 

**To Reproduce**
1. Go to 'https://vitaa-app.netlify.app/search'
2. Click on 'TOPICS'
3. Scroll down to 'Getting the most out of my internship' card.
4. See the typo error in description

**Screenshots**
![Typo Issue](https://user-images.githubusercontent.com/64259328/156029497-80ec6c32-6b01-4964-a1be-07daf65f72f6.png)

I would like to fix this under GSSOC 22. Kindly assign me this issue.

**Comment by Rishabh-malhotraa** [comment]
Can you please check for more typos that might exist and fix all of them together?
You need to change this [file](https://github.com/Rishabh-malhotraa/Vita/blob/main/client/src/data/topics.ts)

**Comment by indraantoor** [comment]
Yes Sure. I'll do it.
