### ISSUE TITLE
Request to add a github action for both issues and PRs 

### ISSUE THREAD

**Issue by Jassi10000** [Rishabh-malhotraa/Vita#41]
**Is your feature request related to a problem? Please describe.**

While opening issues / making PRs ,keeping a check of few things is very necessary

* Providing a valid title
* Provding a nice description
* While making the PR , tagging the issue

**Describe the solution you'd like**
For this I would like to add a github action to this repository

**Describe alternatives you've considered**

**Additional context**

**Comment by Rishabh-malhotraa** [comment]
@Jassi10000 similar to #32

**Comment by Jassi10000** [comment]
> @Jassi10000 similar to #32

Ohh , but its only for PRs
