### ISSUE TITLE
Add meta data to index.html

### ISSUE THREAD

**Issue by Rishabh-malhotraa** [Rishabh-malhotraa/Vita#42]
Currently, the metadata which comes in handy for the preview link is set to the default value of "this app was created by create-react-app"

<img width="1000" alt="image" src="https://user-images.githubusercontent.com/54576074/156406491-1f48b1b2-8a26-492a-804e-84c94edbd5eb.png">

Change it to:

> Vita connects college graduates, alumni, and faculty to revive the culture of mentorship and foster a more connected and engaged community.

files where changes need to be made
https://github.com/Rishabh-malhotraa/Vita/blob/main/client/public/index.html

# Bonus
If you can search other metadata we can add to our index.html to improve SEO and link previews that would be great!

**Comment by indraantoor** [comment]
I am thinking of adding the meta description tag and the meta char set tag. They both are good to have for SEO.

Are you planning on doing something with Structured Markup too, it will help with rich snippets and that is definitely best to have for SEO. We can use JSON-LD for that.

**Comment by zahrabenmohamed** [comment]
I am going to add an icon in the metadata and also turn the wesite responsive viewport ,title ,,and i will tryu to improve the tag description.My contribution is under GSSOC 2022
