### ISSUE TITLE
Adding a custom page/redirect for the server url

### ISSUE THREAD

**Issue by himakhaitan** [Rishabh-malhotraa/Vita#45]
**Is your feature request related to a problem? Please describe.**
As of now the server URL when accessed shows a summy message. `Server is Running:))`

**Describe the solution you'd like**
I would like to construct an HTML page and make It a bit attractive. I plan to write intermediate CSS and make it as per the theme of the project

**Describe alternatives you've considered**
Another way of solving this can be to send a JSON back or actually redirect to the frontend URL.

**Comment by Rishabh-malhotraa** [comment]
Discussed on Discord, not required
