### ISSUE TITLE
Add limit query parameter on /get-mentors endpoint

### ISSUE THREAD

**Issue by Rishabh-malhotraa** [Rishabh-malhotraa/Vita#46]
Currently our `/get-mentors` end-point returns all the matched mentors, I would like to pass in a query parameter to tell the server how many mentors do we want to fetch

<img width="1185" alt="image" src="https://user-images.githubusercontent.com/54576074/156691394-cc753601-55f1-493b-aaf1-b74f37bd417f.png">

add a query limit to `/get-mentors` endpoint to limit the number of mentors sent to the front-end

`/get-mentors?expertise=All&topic=-1&limit=10`  
should only send 10 mentors

Files to edit:
https://github.com/Rishabh-malhotraa/Vita/blob/main/api/src/controllers/api-controller.ts#L6
(and files in a client who is making a request to this endpoint
)

**Comment by Lalit3716** [comment]
Can I work on this?
I know how to solve this I will use limit method on Mongoose Model.
