### ISSUE TITLE
Adding a Footer Component

### ISSUE THREAD

**Issue by SidharthMishra-07** [Rishabh-malhotraa/Vita#50]
Adding a footer component as requested

![VitaFooter](https://user-images.githubusercontent.com/77619346/156752845-733c2911-ab17-4395-b4f6-6983a102766a.png)

**Comment by the-halfbloodprince** [comment]
@Rishabh-malhotraa I'm a GSSoC contributor and would like to work on this. Would you assign this to me please if available?

**Comment by Lalit3716** [comment]
Are you working on this @SidharthMishra-07 ?
If not, can I work on it @Rishabh-malhotraa ?

**Comment by SidharthMishra-07** [comment]
@Rishabh-malhotraa Can you assign me as well ? Can we both work on it?
