### ISSUE TITLE
Adding Vita App's Meet Page in Documentation (i.e. README.md)

### ISSUE THREAD

**Issue by shivam123-dev** [Rishabh-malhotraa/Vita#54]
I am GSSOC'22 contributor. So, @Rishabh-malhotraa kindly assign this issue to me. So that I can update the documentation.

**Comment by Rishabh-malhotraa** [comment]
What do you plan to add?

**Comment by shivam123-dev** [comment]
In the documentation there is no description about Vita App's Meet Page. Just want to add it @Rishabh-malhotraa

**Comment by Rishabh-malhotraa** [comment]
I don't think so its required, I only want to add things on readme which are only essential

**Comment by shivam123-dev** [comment]
Ok sir
