### ISSUE TITLE
Implement Login Using JWT Web tokens 

### ISSUE THREAD

**Issue by Rahul-go1503** [Rishabh-malhotraa/Vita#58]
### Description

When  a user wants to login with their email and password we use jwt tokens for authorization.
I want to work on this issue under GSSoc'22.

### Domain

Backend Dev (Express)

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rishabh-malhotraa/Vita/blob/main/CODE%20OF%20CONDUCT.md) of this project.

### Resources (to implement JWT)

https://www.youtube.com/watch?v=7Q17ubqLfaM&t=2s
https://www.youtube.com/watch?v=F-sFp_AvHc8&t=6s

**Comment by AdnanMuzavor** [comment]
Can you please assign this issue to me @Rishabh-malhotraa . Or is it already assigned?

**Comment by gaurikapoplai21** [comment]
Hey, can you assign this to me, if not already assigned?

**Comment by Rahul-go1503** [comment]
@Rishabh-malhotraa I would also like to work on this. If @gaurikapoplai21 don't mind can you also assign to me ? we can work together

**Comment by SatabrataPaul-GitAc** [comment]
Hello 
I am an active participant of GSSOC'22 
I have already contributed to other projects in the past 2 weeks 
Can I work on this issue ?
I would like to contribute to this project

**Comment by Rishabh-malhotraa** [comment]
> Hello I am an active participant of GSSOC'22 I have already contributed to other projects in the past 2 weeks Can I work on this issue ? I would like to contribute to this project

Hello @SatabrataPaul-GitAc its currently being worked on, would you like to work on something else, there is an issue regarding SMTP server, maybe you can look at that

**Comment by SatabrataPaul-GitAc** [comment]
Yaa sure
Can you assign me with that issue
