### ISSUE TITLE
Add OAuth - Google LinkedIn

### ISSUE THREAD

**Issue by Rishabh-malhotraa** [Rishabh-malhotraa/Vita#6]
## Ability to log in as a mentor/mentee

_**send mentor/mentee information as query parameter while signing up? I can think this is one way to do this but if someone has a better alternative; do mention that in the comments of this issue**_

Oauth Using LinkedIn - Facebook - Google - Github

<img width="1112" alt="image" src="https://user-images.githubusercontent.com/54576074/145148967-78885a47-305e-4ec9-aa3e-475d2a58db05.png">

<img width="1110" alt="image" src="https://user-images.githubusercontent.com/54576074/145149025-e593bbcf-0387-4a66-aa41-a9bac932b0ef.png">

---

## Conditionally display form if the mentor hasn't filled out all the details

After Logging in, if you chose the mentor option, I would like you to display the mentor a form filling out mentor details if he hasn't filled them yet.

All The following data needs to be captured before adding the following person as a mentor, only after adding this should mentor registration be completed.

https://github1s.com/Rishabh-malhotraa/Vita/blob/HEAD/api/src/Models/User.ts#L23-L45

``` js
const MentorSchema = new Schema<MentorSchemaType>({
  user_id: { type: String },
  first_name: { type: String },
  last_name: { type: String },
  image_link: { type: String },
  job_title: { type: String },
  company: { type: String },
  description: { type: [String] },
  expertise: { type: [String] },
  language: { type: [String] },
  linkedIn: String,
  is_mentoring: Boolean,
  topics: [Number],
  time_slot: {
    monday: { type: Duration },
    tuesday: { type: Duration },
    wednesday: { type: Duration },
    thursday: { type: Duration },
    friday: { type: Duration },
    saturday: { type: Duration },
    sunday: { type: Duration },
  },
});
```

**Use Mongo Sessions for storing session data to local storage!**

**Comment by Rishabh-malhotraa** [comment]
https://www.7todos.com/signin

**Comment by sagnik2001** [comment]
Can I work on this under GSSoC 22

**Comment by Rishabh-malhotraa** [comment]
Great, can you please tell me how do you plan to solve the issue, so that we are on the same page? If I', convinced that you understand what needs to be done, I'll assign you the issue

**Comment by sagnik2001** [comment]
Sure, are you asking about adding an OAuth authentication to it ?? If yes, then I tell my method how to progress

**Comment by Rishabh-malhotraa** [comment]
Yes @sagnik2001 how do you plan to add OAuth, my reason for asking is not to test you but to make sure that you would be able to solve the issue without much help from the mentors, because this is a relatively difficult issue

**Comment by sagnik2001** [comment]
Yes yes, I got it I will use an npm package namely react-google-login which will be quite helpful for me adding a google OAuth authentication to it. I would use the components of the package ?? Are we okay?

**Comment by Rishabh-malhotraa** [comment]
With `react-google-login` we would just do authentication from the frontend, and we would not be able to maintain sessions, i.e. every time a user comes to the website, he needs to login again to verify. There is no layer of persistence.

Can you go through what passport-js is
https://www.youtube.com/playlist?list=PL4cUxeGkcC9jdm7QX143aMLAqyM-jTZ2x (old, I followed this when I was learning authentication)
https://www.youtube.com/watch?v=F-sFp_AvHc8 (new video, looks high quality)

**Comment by sagnik2001** [comment]
Yes I can use docs of "passport-js" and can work it upon

**Comment by Rishabh-malhotraa** [comment]
Great, I'll assign you the issue, once you understand how to implement PassportJS.
Its not easy take your time, it can take up to a week to truly grasp how auth works

**Comment by sagnik2001** [comment]
Okay, I look through the docs but there is an alternative of using firebase also which has its own OAuth ??

**Comment by Rishabh-malhotraa** [comment]
Using OAuth with firebase makes sense when we are using firebase DB, but we are using express and MongoDB, so to your question no we cannot use firebase in this scenario.

**Comment by sagnik2001** [comment]
Okay, I looked through "PassportJS" and try to implement it.

**Comment by sagnik2001** [comment]
Is this issue is under GSSoC 22??

**Comment by Rishabh-malhotraa** [comment]
> Is this issue is under GSSoC 22??

Yes, can you please stop spamming on github issues, these kind of questions are better suited for discord sever.

**Comment by gaurikapoplai21** [comment]
Hey is this issue assigned to anyone yet?

**Comment by Rishabh-malhotraa** [comment]
Not yet

**Comment by gaurikapoplai21** [comment]
Yes, I was going through the passport-js playlist you mentioned above. Can this be assigned to me please?

**Comment by DevRish** [comment]
Hi, I am willing to work on this, please assign it to me.
