### ISSUE TITLE
Add Makefile 

### ISSUE THREAD

**Issue by Rishabh-malhotraa** [Rishabh-malhotraa/Vita#65]
### Description

Transfer the build scripts from `package.json` to Makefile -- it would give more control over what we can do, moving further on

### Domain

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rishabh-malhotraa/Vita/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by Harshil-Jani** [comment]
Hey ! @Rishabh-malhotraa I would like to take up this.

**Comment by Rishabh-malhotraa** [comment]
@Harshil-Jani Are you aware of what a Makefile does?

**Comment by Harshil-Jani** [comment]
@Rishabh-malhotraa It just helps in compiling the commands altogether so we don't have to go through all installation steps. All we have to do is execute the makefile using `make` commmand. Although I have never written any Makefiles yet. But, I have used this for installing many OSS.
